[package]
name = "croque"
version = "0.1.0"
edition = "2021"
keywords = [
    "bash",
    "fish",
    "shell",
    "prompt",
    "zsh",
]


[dependencies]
aho-corasick = "0.7"
ansi_term = "0.12"
clap = { version = "4.1", features = ["derive"] }
dirs = "4.0"
git2 = { version = "0.16", default-features = false }
hostname = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"

[target."cfg(not(windows))".dependencies]
users = "0.11"
