[package]
name = "croque"
version = "0.1.0"
edition = "2021"
keywords = [
    "bash",
    "fish",
    "shell",
    "prompt",
    "zsh",
]


[dependencies]
clap = { version = "4.1", features = ["derive"] }
git2 = { version = "0.16", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
